# Generated by Django 3.2.8 on 2024-07-17 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_auto_20240717_0827'),
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'verbose_name': 'Квест', 'verbose_name_plural': 'Квесты'},
        ),
        migrations.AlterModelOptions(
            name='questdone',
            options={'verbose_name': 'Выполненный квест', 'verbose_name_plural': 'Выполненные квесты'},
        ),
        migrations.AlterModelOptions(
            name='rurwithdraw',
            options={'verbose_name': 'Выплата', 'verbose_name_plural': 'Выплаты'},
        ),
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='is_hide',
            field=models.BooleanField(default=False, verbose_name='Скрытый'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='is_major',
            field=models.BooleanField(default=False, verbose_name='Особенный'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='rur_add',
            field=models.CharField(default='', max_length=100, verbose_name='Дает рублей'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='score_add',
            field=models.CharField(default='', max_length=100, verbose_name='Дает баллов'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='score_need',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Нужно баллов'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='questdone',
            name='quest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quests.quest', verbose_name='Квест'),
        ),
        migrations.AlterField(
            model_name='questdone',
            name='rub',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Рубли'),
        ),
        migrations.AlterField(
            model_name='questdone',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='questdone',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tgbot.user', verbose_name='ТГ-пользователь'),
        ),
        migrations.AlterField(
            model_name='rurwithdraw',
            name='rub',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Рубли'),
        ),
        migrations.AlterField(
            model_name='rurwithdraw',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tgbot.user', verbose_name='ТГ-пользователь'),
        ),
    ]
