# Generated by Django 3.2.8 on 2021-11-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
