# Generated by Django 3.2.8 on 2021-11-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_user_is_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identificator',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
