# Generated by Django 3.2.8 on 2024-07-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_user_identificator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ТГ-пользователь', 'verbose_name_plural': 'ТГ-пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=256, verbose_name='ТГ-first_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identificator',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='ТГ-last_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='quests_done_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Квесты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rub_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Рубли'),
        ),
        migrations.AlterField(
            model_name='user',
            name='score_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ТГ-id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='ТГ-username'),
        ),
    ]
